apiVersion: v1
kind: Service
metadata:
  name: ticket-backend
  namespace: ticket-system
  labels:
    app: ticket-backend
    app.kubernetes.io/name: ticket-backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: ticket-backend

