apiVersion: v1
kind: Service
metadata:
  name: ticket-db
  namespace: ticket-system
  labels:
    app: ticket-db
    app.kubernetes.io/name: ticket-db
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: ticket-db

