apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ticket-system
  - ../../base/portainer
  - ../../base/networking

patches:
  - path: patches/db-node-affinity.yaml
  - path: patches/replicas-and-affinity.yaml
